import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Swap from '../components/Swap'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rock Token Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="TokenImage"></div>
      <Header />
      <div class="intro">
        <p>Buy and Sell Rock Tokens in exchange of Ethers.</p>
      </div>
      <div class="rate">
        <p>1 ETH = 100 Rock Tokens (RCK)</p>
      </div>
      <Swap />
    </div>
  )
}
